// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iugkcwazimcucqocclfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1Z2tjd2F6aW1jdWNxb2NjbGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjk3MTIsImV4cCI6MjA1ODgwNTcxMn0.9N3V6woCsLgc-KHlcUUP9k2-qV_FntAW1OdvctMMhpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);